export const FETCH_USER = "FETCH_USER";

export const GET_PROJECTS = "GET_PROJECTS";
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const WIPE_PROJECTS = "WIPE_PROJECTS";

export const GET_FEATURES = "GET_FEATURES";
export const UPDATE_FEATURES = "UPDATE_FEATURES";
export const DELETE_FEATURE = "DELETE_FEATURE";
export const WIPE_FEATURES = "WIPE_FEATURES";

export const GET_COMMENTS = "GET_COMMENTS";
export const UPDATE_COMMENTS = "UPDATE_COMMENTS";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const WIPE_COMMENTS = "WIPE_COMMENTS";
export const APPROVE_COMMENT = "APPROVE_COMMENT";
